package dungeoncrawler;

import dungeoncrawler.BuildLevel;

// Diese Klasse laedt die Level aus einer Datei und gibt die ausgelesenen
// Informationen an die Labels der BuildLevel.java weiter.

public class LoadLevel {


	/**
	 * @param args
	 * @return 
	 * @return 
	 * @return 
	 */
	public static String Current_LevelMap = null;
	public static int PosStartX;
	public static int PosStartY;
	public static int DoorX;
	public static int DoorY;
	public static int counter = 0;
	
	
	public static String getCurrent_LevelMap() {
		
		return Current_LevelMap;
	}
	
	
	
	public static int getPlayerPosStartX(int aktuelles_level) {
		/*
		 * String StringPosX = null;
		 * StringPosX = Current_LevelMap.substring(299, 3);
		 * PosStartX = Integer.parseInt(StringPosX);
		 */
		if (aktuelles_level == 1) {
			PosStartX = 30;
		} 
		else if (aktuelles_level == 3) {
			PosStartX = 0;
		} 
		else if (aktuelles_level == 5) {
			PosStartX = 0;
		} 
		else if (aktuelles_level == 7) {
			PosStartX = 285;
		} 
		else if (aktuelles_level == 9) {
			PosStartX = 195;
		} 
		else {
			PosStartX = 143;
		}
		return PosStartX;	
	}
	
	public static int getPlayerPosStartY(int aktuelles_level) {
		/*
		 * String StringPosY = null;
		 * StringPosY = Current_LevelMap.substring(302, 3);
		 * PosStartY = Integer.parseInt(StringPosY);
		 */
		if (aktuelles_level == 1) {
			PosStartY = 225;
		} 
		else if (aktuelles_level == 3) {
			PosStartY = 75;
		} 
		else if (aktuelles_level == 5) {
			PosStartY = 180;
		} 
		else if (aktuelles_level == 7) {
			PosStartY = 180;
		} 
		else if (aktuelles_level == 9) {
			PosStartY = 195;
		} 
		else {
			PosStartY = 127;
		}
		return PosStartY;	
	}
	
	
	
	public static String main(int current_level, int position) {
		String output = null;

		
		// ############################################
		// Hier fehlt die Datei-Import funktion! (Nils)
		// Levelparameter einzelnd eingelesen
		// ############################################
		
			if (BuildLevel.Current_Level == 1) {
				Current_LevelMap = "PPPPPPPPPPWWWWWWWWWWPWWWWWWWWPWWPPPPWWWWPWWWWWWWWPWWPWWPWWWWPWWWWWWWWPWWPWWPWWWWPWWWWWWWWPWWPWWPPPPDPWWWWWWWWPPPPWWWWWWWPWWWWWWWWPWWPWWWWWWWPPPWWWWWWPWWPWWWWWWWWWPWWWWWWPWWPWWWWWWWWWPPPPPPPPWWPWWWWWWWWWPWWWWWWPWWPPPPWWWWWWPWWWWWWPWWPWWPWWWWWWPWWWWWWPWWPWWPWWWWWWPWWWWWWPWWPWWPWWWWWWDWWWWWWSWWSWWSWWWW225030285075";
			} else if (current_level == 2) {
				Current_LevelMap = "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW225030285075";
			} 
			
			  else if (current_level == 3) {
				Current_LevelMap = "WWWPPPPPPPWWWWWPPPPWWWWPWWWWWPWWWWWPWWPWWWWPWWWWWPWWWWWPWWPWWWWPWWWWWPWWWWWPWWPWDPPPWWWWWPWWWWWPWWPWWWWPWWWWWPPPPPPPWWPWWWWPPPPPPPWWWWWWWWPWWWWPWWWWWPWWWWWWWWPWSPPPWWWWWPPPPPPPWWPWWWWPPPPPPPWWWWWPWWPWWWWPWWWWWPWWWWWPWWPWWWWPWWWWWPWWWWWPWWPWWWWPWWWWWPWWWWWPWWPWWWWPWWWWWPWWWWWPWWPWSPPPWWWWWDWWWWWWWWWW225030285075";	
			} else if (current_level == 4) {
				Current_LevelMap = "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW225030285075";	
			} else if (current_level == 5) {
				Current_LevelMap = "WSWWWSWWWDWWWWSWWWWWWPWWWPWWWPWWWWPWWWWWWPPPPPPPPPWWWWPPPPPWWPWWWPWWWWWWWWPWWWPWSPWWWPWWWWWWWWPWWWPWWPWWWPWWWWWWWWPWWWPWWPPPPPPPPPPPPPPWWWPWWWWWWPWWWWWWWWWWWWPWWWWWWSWWWWWWWWWWWWPWWWWWWWWWWWWWWWWWSPPSWWWWWWWWWWWWWWWWWWPWDPPPPWWWPPPPPPPWWWPWWWWWPWWWPWWWWWPWWWPWWWWWPWWWPWWWWWPWWWPWWWWWPPPPPWWWWWPPPPPW225030285075";	
			} else if (current_level == 6) {
				Current_LevelMap = "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW225030285075";	
			} else if (current_level == 7) {
				Current_LevelMap = "WWWWWWWWWWWWWWWWWWWWWPPPPPPPPPPPPPPPPWWWWPWWWWWWWWWWWWWWPWWWWPPPPPPPPPPPPPPWPWWWWWWWWWWWWWWWWWPWPWWWWPPPPPPPPPPWWWPWPWWWWPWWWWWWWWPWWWPWPWWWWPPPPPPPSWPWWWPWPWWWWPWWWWWWWWPPSWPWPPPSWPWWWWWWWWPWWWPWPWWWSPPPPPPWWWPWWWPWPWWWWPWWWWPWWWPPPPPWPPPDWPPPWWPWWWWWWWPWWWWWWPWPWWPWWWWWWWPPPPPSWSWSWWDWWWWWWWWWWWWW225030285075";	
			} else if (current_level == 8) {
				Current_LevelMap = "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW225030285075";	
			} else if (current_level == 9) {
				Current_LevelMap = "SPPPPPPWSWWWWWWWWWWWSPSSSSPPPWWWWPPPPPPWSPPPPPWWPPPSSSPSSSPSSPSSSSWWWSPPPSPPPSPSWPWWWWDWWWWWPSSSPSPSSPPWWPPPWSSWPSPPPSPSWSPWWPPPWSPPPSPSSSPSWPPWWPSSWSPWWSPPPSPSWPSWSPPPPPPWWSSSPSPPWPPWSSSSSSWWPPPPPSSPWSPSSPPPPPPPPWWWWWSPWPPWWPWWWWWWSSSWWWPPWPWWWPPPPPPPPDSWWWPSWPWWWSWWWWWWSSSWWWPSWPPPPPPPPPPPPPPPPPPP225030285075";	
			} else if (current_level == 10) {
				Current_LevelMap = "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW225030285075";	
			}	
			
			char[] SingleChar = Current_LevelMap.toCharArray();
			
			String StrP = "P";
			char[] ChaP = StrP.toCharArray();
			
			String StrW = "W";
			char[] ChaW = StrW.toCharArray();
			
			String StrD = "D";
			char[] ChaD = StrD.toCharArray();
			
			String StrS = "S";
			char[] ChaS = StrS.toCharArray();
			
			if (SingleChar[position] == ChaP[0]) {
				output = "/dungeoncrawler/path.PNG";			
			}
			
			else if (SingleChar[position] == ChaS[0]) {
				output = "/dungeoncrawler/falle.PNG";			
			}
			
			else if (SingleChar[position] == ChaW[0]) {
				output = "/dungeoncrawler/wall.PNG";			
			}
			
			else if (SingleChar[position] == ChaD[0]) {
				output = "/dungeoncrawler/door.PNG";
			}	
			 
		return output;
		// TODO Auto-generated method stub
		

	}

}
